"use client";
import { useState } from "react";
async function postJson(url: string, payload: object) { const res = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); return res.json(); }
export function AdminPanel() {
  const [postForm, setPostForm] = useState({ title: "", description: "", tags: "", date: new Date().toISOString().slice(0, 10), content: "" });
  const [thoughtForm, setThoughtForm] = useState({ content: "", images: "" });
  const [status, setStatus] = useState("");
  return <div className="space-y-10"><div className="rounded-3xl border border-zinc-100 p-6 dark:border-zinc-900"><h2 className="mb-4 text-xl font-semibold">发布博客文章</h2><div className="grid gap-4"><input className="rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950" placeholder="标题" value={postForm.title} onChange={(e) => setPostForm({ ...postForm, title: e.target.value })} /><input className="rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950" placeholder="摘要" value={postForm.description} onChange={(e) => setPostForm({ ...postForm, description: e.target.value })} /><input className="rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950" placeholder="标签，逗号分隔" value={postForm.tags} onChange={(e) => setPostForm({ ...postForm, tags: e.target.value })} /><input className="rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950" type="date" value={postForm.date} onChange={(e) => setPostForm({ ...postForm, date: e.target.value })} /><textarea className="min-h-[260px] rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950" placeholder="Markdown 正文" value={postForm.content} onChange={(e) => setPostForm({ ...postForm, content: e.target.value })} /><button className="rounded-xl bg-zinc-900 px-5 py-3 text-white dark:bg-white dark:text-zinc-950" onClick={async () => { setStatus("发布中..."); const result = await postJson("/api/admin/publish-post", postForm); setStatus(result.ok ? `已发布：${result.path}` : `发布失败：${result.reason}`); }}>发布文章</button></div></div><div className="rounded-3xl border border-zinc-100 p-6 dark:border-zinc-900"><h2 className="mb-4 text-xl font-semibold">发布想法</h2><div className="grid gap-4"><textarea className="min-h-[180px] rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950" placeholder="写一条短内容..." value={thoughtForm.content} onChange={(e) => setThoughtForm({ ...thoughtForm, content: e.target.value })} /><input className="rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950" placeholder="图片 URL，多张用逗号分隔" value={thoughtForm.images} onChange={(e) => setThoughtForm({ ...thoughtForm, images: e.target.value })} /><button className="rounded-xl bg-zinc-900 px-5 py-3 text-white dark:bg-white dark:text-zinc-950" onClick={async () => { setStatus("发布中..."); const result = await postJson("/api/admin/publish-thought", thoughtForm); setStatus(result.ok ? `已发布：${result.path}` : `发布失败：${result.reason}`); }}>发布想法</button></div></div><div className="rounded-2xl border border-dashed border-zinc-200 p-4 text-sm text-zinc-500 dark:border-zinc-800 dark:text-zinc-400">{status || "后台已就绪。配置好 GITHUB_TOKEN 等环境变量后，发布会直接写入你的 GitHub 仓库。"}</div></div>;
}
